# CoreItems Configuration

# Settings for custom item namespaces
namespaces:
  # Enable the namespace system
  enabled: true
  
  # Should the plugin load namespaces on startup
  load-on-startup: true
  
  # Default namespace to use when no namespace is specified
  default-namespace: "default"
  
  # Directory where namespace folders are stored
  directory: "customs"

# Global settings for item interactions
item-interactions:
  # Global cooldown between all item interactions in milliseconds
  # This can be overridden per-item in customs.yml with 'cooldown' property
  global-cooldown: 500
  
  # Cooldown message settings
  cooldown-message-enabled: false
  cooldown-message: '&cThis item is on cooldown!'
  cooldown-message-interval: 4
  

# Player data storage settings
player-data:
  # Enable inventory tracking of player custom items
  enabled: true
  
  # Automatic inventory scan settings
  auto_scan:
    # Enable automatic scanning and saving
    enabled: true
    
    # Interval between automatic scans (in milliseconds)
    interval: 300000  # 5 minutes

# Settings for the GUI menu
gui:
  # Enable the GUI menu system
  enabled: true
  
  # Title for the main menu
  main-menu-title: "CoreItems: Namespaces"
  
  # Title for namespace items menus
  items-menu-title: "CoreItems: {namespace}"
  
  # Border item material (any valid Minecraft item, or 'NONE' for no border)
  # Examples: BLACK_STAINED_GLASS_PANE, BLUE_STAINED_GLASS_PANE, BARRIER, etc.
  border-item: "BLACK_STAINED_GLASS_PANE"
  
  # Maximum items per page in the namespace browser
  namespaces-per-page: 14
  
  # Maximum items per page in the items browser
  items-per-page: 21

# Settings for search functionality
search:
  # Enable the namespace search feature
  enabled: true
  
  # Search timeout in seconds
  timeout: 30
  
  # Search button material
  button-material: "OAK_SIGN"
  
  # Title for search results menu
  results-title: "Search Results: {query}"
